In [1]:
import numpy as np
generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))
missing_grades = np.isnan(grades[:, 0])
third_column = np.where(missing_grades, grades[:, 1], grades[:, 0])
grades_with_third_column = np.column_stack((grades, third_column))
print(grades_with_third_column)

[[7. 1. 7.]
 [2. 2. 2.]
 [2. 8. 2.]
 [9. 3. 9.]
 [8. 9. 8.]
 [5. 2. 5.]
 [8. 2. 8.]
 [7. 6. 7.]
 [9. 2. 9.]
 [8. 5. 8.]]
